### ISSUE TITLE
ValueError: 'out/app_engine/' unrecognized boolean; known booleans are 'true', 'yes', '1', 'false', 'no', '0'

### ISSUE THREAD

**Issue by Sn0rt** [webrtc/apprtc#116]
hi, I have follow the readme to install apprtc in Ubunut14.04 which was new installtion.
Although I read the readme again and again , not found the  mistake was I do.

'''

sn0rt@ubuntu-lab:~/workspace/apprtc$ ../google_appengine/dev_appserver.py --skip_sdk_update_check out/app_engine/
Traceback (most recent call last):
  File "../google_appengine/dev_appserver.py", line 83, in <module>
    _run_file(__file__, globals())
  File "../google_appengine/dev_appserver.py", line 79, in _run_file
    execfile(_PATHS.script_file(script_name), globals_)
  File "/home/sn0rt/workspace/google_appengine/google/appengine/tools/devappserver2/devappserver2.py", line 985, in <module>
    main()
  File "/home/sn0rt/workspace/google_appengine/google/appengine/tools/devappserver2/devappserver2.py", line 975, in main
    options = PARSER.parse_args()
  File "/usr/lib/python2.7/argparse.py", line 1690, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/usr/lib/python2.7/argparse.py", line 1722, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/lib/python2.7/argparse.py", line 1928, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/usr/lib/python2.7/argparse.py", line 1868, in consume_optional
    take_action(action, args, option_string)
  File "/usr/lib/python2.7/argparse.py", line 1796, in take_action
    action(self, namespace, argument_values, option_string)
  File "/home/sn0rt/workspace/google_appengine/google/appengine/tools/boolean_action.py", line 63, in __call__
    setattr(namespace, self.dest, BooleanParse(values))
  File "/home/sn0rt/workspace/google_appengine/google/appengine/tools/boolean_action.py", line 78, in BooleanParse
    (values, ', '.join(repr_values)))
ValueError: 'out/app_engine/' unrecognized boolean; known booleans are 'true', 'yes', '1', 'false', 'no', '0'.

'''

**Comment by chuckhays** [comment]
> ValueError: 'out/app_engine/' unrecognized boolean; known booleans are 'true', 'yes', '1', 'false', 'no', '0'.

It looks like --skip_sdk_update requires a boolean value to be provided, running with --help shows:
>   --skip_sdk_update_check [SKIP_SDK_UPDATE_CHECK]
>                        skip checking for SDK updates (if false, use
>                        .appcfg_nag to decide) (default: False)

Can you try your command as:
```
sn0rt@ubuntu-lab:~/workspace/apprtc$ ../google_appengine/dev_appserver.py --skip_sdk_update_check true out/app_engine/
```
