### ISSUE TITLE
Python tests fail locally after the webtest change

### ISSUE THREAD

**Issue by jiayliu** [webrtc/apprtc#37]
https://github.com/webrtc/samples/issues/326

Running "shell:runPythonTests" (shell) task
apprtc_test (unittest.loader.ModuleImportFailure) ... ERROR

ERROR: apprtc_test (unittest.loader.ModuleImportFailure)

ImportError: Failed to import test module: apprtc_test
Traceback (most recent call last):
File "/usr/lib/python2.7/unittest/loader.py", line 254, in find_tests
module = self.get_module_from_name(name)
File "/usr/lib/python2.7/unittest/loader.py", line 232, in _get_module_from_name
__import(name)
File "/usr/local/google/home/jiayl/code/apprtc-fork/jiayl-webrtc/samples/web/content/apprtc/apprtc_test.py", line 4, in 
import webtest
File "webtest-master/webtest/init.py", line 9, in 
from webtest.app import TestApp
File "webtest-master/webtest/app.py", line 32, in 
from webtest.response import TestResponse
File "webtest-master/webtest/response.py", line 5, in 
from webtest import forms
File "webtest-master/webtest/forms.py", line 7, in 
from bs4 import BeautifulSoup
ImportError: No module named bs4
phoglundphoglund was assigned by jiayliu on Dec 19, 2014
Jiayang Liu
 Owner
jiayliu commented on Dec 22, 2014
I figured out how to fix it locally:
http://stackoverflow.com/questions/25697184/importerror-no-module-named-bs4

@phoglund

Can you modify the script to check/install the prerequisites since other people may run into this problem as well?
phoglund
 
 phoglund commented on Dec 25, 2014
Yeah, I thought it was already doing that as a part of the make script, and
it appeared to work on the Travis boxes, but I'll make sure it always does
it.

**Comment by phoglund** [comment]
Yeah, the script kind of does the right thing but it won't work if you don't have easy_install on your box. I will try to rewrite the script so it fails cleanly and tells you what you need to do.

**Comment by KaptenJansson** [comment]
@phoglund did you end up doing this?
