### ISSUE TITLE
grunt build warnings.

### ISSUE THREAD

**Issue by chanjungkim** [webrtc/apprtc#605]
I got warnings. How can I fix this? or is this Okay?

I just did it with `--force` option. but I am not sure if it's fine.

```
root@ubuntu:/home/chan/apprtc# grunt build --force
Running "shell:buildAppEnginePackage" (shell) task
  File "./build/build_app_engine_package.py", line 29
    print str(e)
            ^
SyntaxError: invalid syntax
Warning: Command failed: python ./build/build_app_engine_package.py src out/app_engine
  File "./build/build_app_engine_package.py", line 29
    print str(e)
            ^
SyntaxError: invalid syntax
 Used --force, continuing.

Running "shell:genJsEnums" (shell) task
  File "./build/gen_js_enums.py", line 29
    print src_path, '>>>', dst_path
                 ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(t src_path, '>>>', dst_path)?
Warning: Command failed: python ./build/gen_js_enums.py src src/web_app/js
  File "./build/gen_js_enums.py", line 29
    print src_path, '>>>', dst_path
                 ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(t src_path, '>>>', dst_path)?
 Used --force, continuing.

Running "closurecompiler:debug" (closurecompiler) task

Compiling node_modules/webrtc-adapter/out/adapter.js,src/web_app/js/analytics.js,src/web_app/js/appcontroller.js,src/web_app/js/call.js,src/web_app/js/constants.js,src/web_app/js/infobox.js,src/web_app/js/peerconnectionclient.js,src/web_app/js/remotewebsocket.js,src/web_app/js/roomselection.js,src/web_app/js/sdputils.js,src/web_app/js/signalingchannel.js,src/web_app/js/stats.js,src/web_app/js/storage.js,src/web_app/js/util.js,src/web_app/js/windowport.js -> out/app_engine/js/apprtc.debug.js
>> Complete: 264110

Running "grunt-chrome-build:apprtc" (grunt-chrome-build) task
Chrome packaged app build.
Deleting buildDir: out/chrome_app
>> Cannot delete nonexistent file.
Creating empty buildDir: out/chrome_app
Copying resources to buildDir: out/chrome_app
object
out/chrome_app/manifest.json
src/web_app/chrome_app/manifest.json-->out/chrome_app/manifest.json
object
out/chrome_app/js/apprtc.debug.js
out/app_engine/js/apprtc.debug.js-->out/chrome_app/js/apprtc.debug.js
object
out/chrome_app/js/background.js
src/web_app/js/background.js-->out/chrome_app/js/background.js
object
out/chrome_app/js/appwindow.js
src/web_app/js/appwindow.js-->out/chrome_app/js/appwindow.js

Running "grunt-chrome-build-transform" task
Transforming files using jinja.

Running "jinja:chrome-build" (jinja) task
Using context web_app/html/index_template
File "out/chrome_app/appwindow.html" created.

Running "grunt-chrome-build-compress" task
Creating zip file:out/chrome_app/apprtc.zip

Running "compress:chrome-build" (compress) task
>> Compressed 6 files.

Running "grunt-chrome-build-package" task
Skipping creation of Chrome package.

Done, but with warnings.
root@ubuntu:/home/chan/apprtc#
```

**Comment by SunnyVZ777** [comment]
me too

**Comment by webcodepl** [comment]
I resolved this problem installing Python 2.7.16 instead 3.7.4

**Comment by Code-Crash** [comment]
Hi @webcodepl 

I'm facing different issue while grunt build:


```sh
Running "shell:buildAppEnginePackage" (shell) task

Running "shell:genJsEnums" (shell) task
src >>> src/web_app/js

Running "closurecompiler:debug" (closurecompiler) task

Compiling node_modules/webrtc-adapter/out/adapter.js,src/web_app/js/analytics.js,src/web_app/js/enums.js,src/web_app/js/appcontroller.js,src/web_app/js/call.js,src/web_app/js/constants.js,src/web_app/js/infobox.js,src/web_app/js/peerconnectionclient.js,src/web_app/js/remotewebsocket.js,src/web_app/js/roomselection.js,src/web_app/js/sdputils.js,src/web_app/js/signalingchannel.js,src/web_app/js/stats.js,src/web_app/js/storage.js,src/web_app/js/util.js,src/web_app/js/windowport.js -> out/app_engine/js/apprtc.debug.js
Warning: Exception in thread "main" java.lang.UnsupportedClassVersionError: com/google/javascript/jscomp/CommandLineRunner : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:791)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:480)
 Use --force to continue.

Aborted due to warnings.
```

Any solution? or Am I doing something wrong? 
Versions: 
```sh
apprtc ➤ python --version
Python 2.7.16
apprtc ➤ javac --version
javac 13.0.2
apprtc ➤ java --version
java 13.0.2 2020-01-14
Java(TM) SE Runtime Environment (build 13.0.2+8)
Java HotSpot(TM) 64-Bit Server VM (build 13.0.2+8, mixed mode, sharing)
```


Thanks

**Comment by gurdevs** [comment]
Any solutions or updates on this above mentioned error?

**Comment by wood-j** [comment]
I had the same result info but not all the same
When i scroll up all the output, I got some lines like:

```
Loading "jinja.coffee" tasks...ERROR
>> Error: Grunt attempted to load a .coffee file but CoffeeScript was not installed.
>> Please run `npm install --dev coffeescript` to enable loading CoffeeScript.
```

So, I just do:

```
npm install --dev coffeescript
```
 And i build again:

```
Running "shell:buildAppEnginePackage" (shell) task

Running "shell:genJsEnums" (shell) task
src >>> src/web_app/js

Running "closurecompiler:debug" (closurecompiler) task

Compiling node_modules/webrtc-adapter/out/adapter.js,src/web_app/js/analytics.js,src/web_app/js/enums.js,src/web_app/js/appcontroller.js,src/web_app/js/call.js,src/web_app/js/constants.js,src/web_app/js/infobox.js,src/web_app/js/peerconnectionclient.js,src/web_app/js/remotewebsocket.js,src/web_app/js/roomselection.js,src/web_app/js/sdputils.js,src/web_app/js/signalingchannel.js,src/web_app/js/stats.js,src/web_app/js/storage.js,src/web_app/js/util.js,src/web_app/js/windowport.js -> out/app_engine/js/apprtc.debug.js
>> Complete: 276899

Running "grunt-chrome-build:apprtc" (grunt-chrome-build) task
Chrome packaged app build.
Deleting buildDir: out/chrome_app
Creating empty buildDir: out/chrome_app
Copying resources to buildDir: out/chrome_app
object
out/chrome_app/manifest.json
src/web_app/chrome_app/manifest.json-->out/chrome_app/manifest.json
object
out/chrome_app/js/apprtc.debug.js
out/app_engine/js/apprtc.debug.js-->out/chrome_app/js/apprtc.debug.js
object
out/chrome_app/js/loopback.js
out/app_engine/js/loopback.js-->out/chrome_app/js/loopback.js
object
out/chrome_app/third_party/pako/pako.min.js
out/app_engine/third_party/pako/pako.min.js-->out/chrome_app/third_party/pako/pako.min.js
object
out/chrome_app/css/main.css
out/app_engine/css/main.css-->out/chrome_app/css/main.css
object
out/chrome_app/images/apprtc-128.png
out/app_engine/images/apprtc-128.png-->out/chrome_app/images/apprtc-128.png
object
out/chrome_app/images/apprtc-16.png
out/app_engine/images/apprtc-16.png-->out/chrome_app/images/apprtc-16.png
object
out/chrome_app/images/apprtc-22.png
out/app_engine/images/apprtc-22.png-->out/chrome_app/images/apprtc-22.png
object
out/chrome_app/images/apprtc-32.png
out/app_engine/images/apprtc-32.png-->out/chrome_app/images/apprtc-32.png
object
out/chrome_app/images/apprtc-48.png
out/app_engine/images/apprtc-48.png-->out/chrome_app/images/apprtc-48.png
object
out/chrome_app/js/background.js
src/web_app/js/background.js-->out/chrome_app/js/background.js
object
out/chrome_app/js/appwindow.js
src/web_app/js/appwindow.js-->out/chrome_app/js/appwindow.js

Running "grunt-chrome-build-transform" task
Transforming files using jinja.

Running "jinja:chrome-build" (jinja) task
Using context web_app/html/index_template
File "out/chrome_app/appwindow.html" created.

Running "grunt-chrome-build-compress" task
Creating zip file:out/chrome_app/apprtc.zip

Running "compress:chrome-build" (compress) task
>> Compressed 18 files.

Running "grunt-chrome-build-package" task
Skipping creation of Chrome package.

Done.
```

Finally done, May be this will help.

**Comment by wcxdhr** [comment]
> Hi @webcodepl
> 
> I'm facing different issue while grunt build:
> 
> ```shell
> Running "shell:buildAppEnginePackage" (shell) task
> 
> Running "shell:genJsEnums" (shell) task
> src >>> src/web_app/js
> 
> Running "closurecompiler:debug" (closurecompiler) task
> 
> Compiling node_modules/webrtc-adapter/out/adapter.js,src/web_app/js/analytics.js,src/web_app/js/enums.js,src/web_app/js/appcontroller.js,src/web_app/js/call.js,src/web_app/js/constants.js,src/web_app/js/infobox.js,src/web_app/js/peerconnectionclient.js,src/web_app/js/remotewebsocket.js,src/web_app/js/roomselection.js,src/web_app/js/sdputils.js,src/web_app/js/signalingchannel.js,src/web_app/js/stats.js,src/web_app/js/storage.js,src/web_app/js/util.js,src/web_app/js/windowport.js -> out/app_engine/js/apprtc.debug.js
> Warning: Exception in thread "main" java.lang.UnsupportedClassVersionError: com/google/javascript/jscomp/CommandLineRunner : Unsupported major.minor version 52.0
> 	at java.lang.ClassLoader.defineClass1(Native Method)
> 	at java.lang.ClassLoader.defineClass(ClassLoader.java:791)
> 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
> 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
> 	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
> 	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
> 	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
> 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
> 	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:480)
>  Use --force to continue.
> 
> Aborted due to warnings.
> ```
> 
> Any solution? or Am I doing something wrong?
> Versions:
> 
> ```shell
> apprtc ➤ python --version
> Python 2.7.16
> apprtc ➤ javac --version
> javac 13.0.2
> apprtc ➤ java --version
> java 13.0.2 2020-01-14
> Java(TM) SE Runtime Environment (build 13.0.2+8)
> Java HotSpot(TM) 64-Bit Server VM (build 13.0.2+8, mixed mode, sharing)
> ```
> 
> Thanks

Same issue with you. Have you solved this problem?

**Comment by aknaldemir** [comment]
> I got warnings. How can I fix this? or is this Okay?
> 
> I just did it with `--force` option. but I am not sure if it's fine.
> 
> ```
> root@ubuntu:/home/chan/apprtc# grunt build --force
> Running "shell:buildAppEnginePackage" (shell) task
>   File "./build/build_app_engine_package.py", line 29
>     print str(e)
>             ^
> SyntaxError: invalid syntax
> Warning: Command failed: python ./build/build_app_engine_package.py src out/app_engine
>   File "./build/build_app_engine_package.py", line 29
>     print str(e)
>             ^
> SyntaxError: invalid syntax
>  Used --force, continuing.
> 
> Running "shell:genJsEnums" (shell) task
>   File "./build/gen_js_enums.py", line 29
>     print src_path, '>>>', dst_path
>                  ^
> SyntaxError: Missing parentheses in call to 'print'. Did you mean print(t src_path, '>>>', dst_path)?
> Warning: Command failed: python ./build/gen_js_enums.py src src/web_app/js
>   File "./build/gen_js_enums.py", line 29
>     print src_path, '>>>', dst_path
>                  ^
> SyntaxError: Missing parentheses in call to 'print'. Did you mean print(t src_path, '>>>', dst_path)?
>  Used --force, continuing.
> 
> Running "closurecompiler:debug" (closurecompiler) task
> 
> Compiling node_modules/webrtc-adapter/out/adapter.js,src/web_app/js/analytics.js,src/web_app/js/appcontroller.js,src/web_app/js/call.js,src/web_app/js/constants.js,src/web_app/js/infobox.js,src/web_app/js/peerconnectionclient.js,src/web_app/js/remotewebsocket.js,src/web_app/js/roomselection.js,src/web_app/js/sdputils.js,src/web_app/js/signalingchannel.js,src/web_app/js/stats.js,src/web_app/js/storage.js,src/web_app/js/util.js,src/web_app/js/windowport.js -> out/app_engine/js/apprtc.debug.js
> >> Complete: 264110
> 
> Running "grunt-chrome-build:apprtc" (grunt-chrome-build) task
> Chrome packaged app build.
> Deleting buildDir: out/chrome_app
> >> Cannot delete nonexistent file.
> Creating empty buildDir: out/chrome_app
> Copying resources to buildDir: out/chrome_app
> object
> out/chrome_app/manifest.json
> src/web_app/chrome_app/manifest.json-->out/chrome_app/manifest.json
> object
> out/chrome_app/js/apprtc.debug.js
> out/app_engine/js/apprtc.debug.js-->out/chrome_app/js/apprtc.debug.js
> object
> out/chrome_app/js/background.js
> src/web_app/js/background.js-->out/chrome_app/js/background.js
> object
> out/chrome_app/js/appwindow.js
> src/web_app/js/appwindow.js-->out/chrome_app/js/appwindow.js
> 
> Running "grunt-chrome-build-transform" task
> Transforming files using jinja.
> 
> Running "jinja:chrome-build" (jinja) task
> Using context web_app/html/index_template
> File "out/chrome_app/appwindow.html" created.
> 
> Running "grunt-chrome-build-compress" task
> Creating zip file:out/chrome_app/apprtc.zip
> 
> Running "compress:chrome-build" (compress) task
> >> Compressed 6 files.
> 
> Running "grunt-chrome-build-package" task
> Skipping creation of Chrome package.
> 
> Done, but with warnings.
> root@ubuntu:/home/chan/apprtc#
> ```

Solution?
