### ISSUE TITLE
apprtc + ssl,  WSGI throw exception after idle for some time

### ISSUE THREAD

**Issue by feiyue1206** [webrtc/apprtc#634]
I use the following instruction to startup the apprtc server + ssl, and it works well.

dev_appserver.py --ssl_certificate_path $(mycert) --ssl_certificate_key_path $(mykey) --enable_host_checking false --dev_appserver_log_level info --logs_path=$(logpath)  --host=0.0.0.0 --port=7000 /root/apprtc/out/app_engine 

but after a period time idle , apprtc server goes down and throw exception like this:

> 
> Exception in thread WSGI select:
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
>     self.run()
>   File "/usr/lib/python2.7/threading.py", line 754, in run
>     self.__target(*self.__args, **self.__kwargs)
>   File "/usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/wsgi_server.py", line 166, in _loop_forever
>     self._select()
>   File "/usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/wsgi_server.py", line 188, in _select
>     fd_to_callback[fd]()
>   File "/usr/lib/google-cloud-sdk/platform/google_appengine/lib/cherrypy/cherrypy/wsgiserver/wsgiserver2.py", line 1902, in tick
>     s, ssl_env = self.ssl_adapter.wrap(s)
>   File "/usr/lib/google-cloud-sdk/platform/google_appengine/lib/cherrypy/cherrypy/wsgiserver/ssl_builtin.py", line 52, in wrap
>     keyfile=self.private_key, ssl_version=ssl.PROTOCOL_SSLv23)
>   File "/usr/lib/python2.7/ssl.py", line 933, in wrap_socket
>     ciphers=ciphers)
>   File "/usr/lib/python2.7/ssl.py", line 601, in __init__
>     self.do_handshake()
>   File "/usr/lib/python2.7/ssl.py", line 830, in do_handshake
>     self._sslobj.do_handshake()
> SSLError: [SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:590)

does anyone give an advice ? appreciated!

**Comment by ivandroconradi** [comment]
I'm struggling in this case too

**Comment by einsteinarbert** [comment]
I'm die here too, so so bad :(

**Comment by einsteinarbert** [comment]
> I'm struggling in this case too

did you resolved that issue?

**Comment by feiyue1206** [comment]
i had surrenderred to this problem.

**Comment by einsteinarbert** [comment]
Maybe we need to debug into dev server, I think it worked in the first
time, so second time error maybe in google code make our error for force we
to use Google Cloud deploy??

Vào Th 4, 11 thg 12, 2019 vào lúc 11:05 song <notifications@github.com>
đã viết:

**Comment by einsteinarbert** [comment]
I have a good news, I just add try catch to trunk of code in devappserver2 that raise error: 

> File "/usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/wsgi_server.py", line 166,
I added:
```
try:
  self._select()
except:
  print "error in SSL"
```
And the server of AppRTC is running until now, about 24h without error.
I will update in several days!!
