### ISSUE TITLE
Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by wcxdhr** [webrtc/apprtc#671]
**Description**
When I run `grunt bulid`, there are some warnings:
```
Compiling node_modules/webrtc-adapter/out/adapter.js,src/web_app/js/analytics.js,src/web_app/js/enums.js,src/web_app/js/appcontroller.js,src/web_app/js/call.js,src/web_app/js/constants.js,src/web_app/js/infobox.js,src/web_app/js/peerconnectionclient.js,src/web_app/js/remotewebsocket.js,src/web_app/js/roomselection.js,src/web_app/js/sdputils.js,src/web_app/js/signalingchannel.js,src/web_app/js/stats.js,src/web_app/js/storage.js,src/web_app/js/util.js,src/web_app/js/windowport.js -> out/app_engine/js/apprtc.debug.js
Warning: Exception in thread "main" java.lang.UnsupportedClassVersionError: com/google/javascript/jscomp/CommandLineRunner : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:791)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:480)
 Use --force to continue.
```

After I update my java version, it still happened.
My java infomation:
`java -version`
```
java version "14.0.2" 2020-07-14
Java(TM) SE Runtime Environment (build 14.0.2+12-46)
Java HotSpot(TM) 64-Bit Server VM (build 14.0.2+12-46, mixed mode, sharing)
```

`javac -version`
`javac 14.0.2`

I also set path in .bash_profile: 
```
JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk-14.0.2.jdk/Contents/Home
PATH=$JAVA_HOME/bin:$PATH:.
CLASSPATH=$JAVA_HOME/lib/tools.jar:$JAVA_HOME/lib/dt.jar:.
export JAVA_HOME
export PATH
export CLASSPATH
```

So if there are any solutions or ways to know which java version `grunt build` use?

I tried to use `grunt build --force`, but will miss some .js.
**Steps to reproduce**
grunt build

**Comment by wcxdhr** [comment]
> **Description**
> When I run `grunt bulid`, there are some warnings:
> 
> ```
> Compiling node_modules/webrtc-adapter/out/adapter.js,src/web_app/js/analytics.js,src/web_app/js/enums.js,src/web_app/js/appcontroller.js,src/web_app/js/call.js,src/web_app/js/constants.js,src/web_app/js/infobox.js,src/web_app/js/peerconnectionclient.js,src/web_app/js/remotewebsocket.js,src/web_app/js/roomselection.js,src/web_app/js/sdputils.js,src/web_app/js/signalingchannel.js,src/web_app/js/stats.js,src/web_app/js/storage.js,src/web_app/js/util.js,src/web_app/js/windowport.js -> out/app_engine/js/apprtc.debug.js
> Warning: Exception in thread "main" java.lang.UnsupportedClassVersionError: com/google/javascript/jscomp/CommandLineRunner : Unsupported major.minor version 52.0
> 	at java.lang.ClassLoader.defineClass1(Native Method)
> 	at java.lang.ClassLoader.defineClass(ClassLoader.java:791)
> 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
> 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
> 	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
> 	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
> 	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
> 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
> 	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:480)
>  Use --force to continue.
> ```
> 
> After I update my java version, it still happened.
> My java infomation:
> `java -version`
> 
> ```
> java version "14.0.2" 2020-07-14
> Java(TM) SE Runtime Environment (build 14.0.2+12-46)
> Java HotSpot(TM) 64-Bit Server VM (build 14.0.2+12-46, mixed mode, sharing)
> ```
> 
> `javac -version`
> `javac 14.0.2`
> 
> I also set path in .bash_profile:
> 
> ```
> JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk-14.0.2.jdk/Contents/Home
> PATH=$JAVA_HOME/bin:$PATH:.
> CLASSPATH=$JAVA_HOME/lib/tools.jar:$JAVA_HOME/lib/dt.jar:.
> export JAVA_HOME
> export PATH
> export CLASSPATH
> ```
> 
> So if there are any solutions or ways to know which java version `grunt build` use?
> 
> I tried to use `grunt build --force`, but will miss some .js.
> **Steps to reproduce**
> grunt build

I solved this by set java version to jdk1.8.
