### ISSUE TITLE
Can't start the apprtc dev server

### ISSUE THREAD

**Issue by Epeny14** [webrtc/apprtc#703]
Hello,

I downloaded the apprtc project in the[ Github](https://github.com/webrtc/apprtc) on my computer, then I installed Google App Engine SDK For Python, Node js and Grunt.

After installing Google App Engine SDK I launched the command line to start the project: 
 C:\Program Files (x86)\Google\Cloud SDK> dev_appserver.py ./out/app_engine but I get error messages:

`Traceback (most recent call last):
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\platform\google_appengine\dev_appserver.py", line 96, in <module>
    _run_file(__file__, globals())
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\platform\google_appengine\dev_appserver.py", line 90, in _run_file
    execfile(_PATHS.script_file(script_name), globals_)
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\platform\google_appengine\google\appengine\tools\devappserver2\devappserver2.py", line 613, in <module>
    main()
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\platform\google_appengine\google\appengine\tools\devappserver2\devappserver2.py", line 601, in main
    dev_server.start(options)
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\platform\google_appengine\google\appengine\tools\devappserver2\devappserver2.py", line 277, in start
    env_variables=parsed_env_variables)
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\platform\google_appengine\google\appengine\tools\devappserver2\application_configuration.py", line 940, in __init__
    env_variables)
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\platform\google_appengine\google\appengine\tools\devappserver2\application_configuration.py", line 139, in __init__
    self._config_path)
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\platform\google_appengine\google\appengine\tools\devappserver2\application_configuration.py", line 501, in _parse_configuration
    with open(configuration_path) as f:
IOError: [Errno 2] No such file or directory: './out/app_engine'`

How do I start the project in the command line of Google App Engine SDK?

Thank you in advance for your answers.

**Comment by jksttymm** [comment]
I am also getting same err any update @Epeny14

**Comment by jksttymm** [comment]
Hi @Epeny14 close this issue solved !!! i was mad at the moment
